#this .yaml file contains the paramters 
#that can tweak the dimensions of the diff_drive robot
#without making changes to the urdf file
#wheel base and wheel width are used to find width of chassis of the robot
# width = wheelbase - wheel width
# other parameter specify dimensions as per their names
wheel_width : 0.009
wheel_radius: 0.033
wheel_base : 0.160
chassis_length : 0.138
chassis_thickness: 0.140
encoder_ticks_per_rev: 4096
max_lvel_robot: 0.22
max_rvel_robot: 2.84
max_rvel_motor: 6.35492
max_motor_power : 265
wheel_axle_offset: 0.02