<?xml version="1.0"?>
<robot name="diff_drive" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name="yaml_file" value="$(find nuturtle_description)/config/diff_params.yaml" />
<xacro:property name="a" value="${load_yaml(yaml_file)}"/>

 <!-- Base Link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${a['wheel_radius']}" rpy="0 0 0" />
      <geometry>
          <box size="${a['chassis_length']} ${a['wheel_base']-a['wheel_width']} ${a['chassis_thickness']} "/>
      </geometry>
      <material name="color1">
        <color rgba="0.1 0.3 1 0.6"/>
      </material>
    </visual>
  </link>


   <!-- Right Wheel -->
  <link name="right_wheel">
    <visual>
      <origin xyz="0 ${-1*a['wheel_width']/2} 0" rpy="1.570795 0 0" />
      <geometry>
          <cylinder length="${a['wheel_width']}" radius="${a['wheel_radius']}" />
      </geometry>
      <material name="color2">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
  </link>
  <joint name="right_wheel_axle" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="${-1*(a['chassis_length']/2-a['wheel_radius'])} ${-1*(a['wheel_base']/2-a['wheel_width']/2)} ${a['wheel_radius']}" rpy="0 0 0" /> 
    <axis xyz="0 1 0" />
  </joint>

  <!-- left Wheel -->
  <link name="left_wheel">
    <visual>
      <origin xyz="0 ${1*a['wheel_width']/2} 0" rpy="1.570795 0 0" />
      <geometry>
          <cylinder length="${a['wheel_width']}" radius="${a['wheel_radius']}" />
      </geometry>
      <material name="color3">
        <color rgba="0.3 0.44 0.1 0.6"/>
      </material>
    </visual>
  </link>
  <joint name="left_wheel_axle" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="${-1*(a['chassis_length']/2-a['wheel_radius'])} ${1*(a['wheel_base']/2-a['wheel_width']/2)} ${a['wheel_radius']}" rpy="0 0 0" /> 
    <axis xyz="0 1 0" />
  </joint>

<!-- caster Wheel -->
<link name="caster">
    <visual>
      <origin xyz="0 0 ${-1*(a['wheel_radius']-(a['chassis_thickness']/2))/2}" rpy="0 0 0" />
      <geometry>
          <sphere radius="${(a['wheel_radius']-(a['chassis_thickness']/2))/2}"/>
      </geometry>
      <material name="color4">
        <color rgba="0.8 0.12 1 1"/>
      </material>
    </visual>
  </link>
  <joint name="caster_chassis" type="fixed">
    <parent link="base_link"/>
    <child link="caster"/>
    <origin xyz="${a['chassis_length']/2-(a['wheel_radius']-(a['chassis_thickness']/2))/2} 0 ${-1*a['chassis_thickness']/2 + a['wheel_radius']}" /> 
  </joint>

</robot>